<Project Sdk="Microsoft.NET.Sdk" TreatAsLocalProperty="PublishAot;PublishTrimmed">

    <PropertyGroup>
        <PublishAot>false</PublishAot>
        <PublishTrimmed>false</PublishTrimmed>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);1591</NoWarn>
        <PackageId>AdamE.AppNav</PackageId>
        <Description>UI-platform-agnostic application navigation and URL routing core for .NET applications.</Description>
        <IsAotCompatible>true</IsAotCompatible>
        <AppNavGeneratorTargetFramework>$([System.String]::Concat('net','standard2.0'))</AppNavGeneratorTargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" Version="2026.2.0"/>
        <PackageReference Include="Microsoft.CodeAnalysis.PublicApiAnalyzers" Version="5.6.0" PrivateAssets="all" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0"/>
    </ItemGroup>

    <ItemGroup>
        <AdditionalFiles Include="PublicAPI.Shipped.txt" />
        <AdditionalFiles Include="PublicAPI.Unshipped.txt" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\AdamE.AppNav.Generators\AdamE.AppNav.Generators.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false"
                          PrivateAssets="all"
                          GlobalPropertiesToRemove="PublishAot;IsAotCompatible;IsTrimmable;EnableTrimAnalyzer;EnableAotAnalyzer;PublishTrimmed;TrimMode"/>
        <None Include="..\AdamE.AppNav.Generators\bin\$(Configuration)\$(AppNavGeneratorTargetFramework)\AdamE.AppNav.Generators.dll"
              Pack="true"
              PackagePath="analyzers/dotnet/cs"
              Visible="false"/>
    </ItemGroup>

</Project>
