<Project>
    <PropertyGroup>
        <Authors>Adam Essenmacher</Authors>
        <Company>Adam Essenmacher</Company>
        <Product>AdamE.AppNav</Product>
        <Copyright>Copyright © 2026 Adam Essenmacher</Copyright>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/AdamEssenmacher/AdamE.AppNav</PackageProjectUrl>
        <RepositoryUrl>https://github.com/AdamEssenmacher/AdamE.AppNav.git</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageTags>navigation;application-navigation;router;deep-linking;app-links;url-routing</PackageTags>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <Deterministic>true</Deterministic>
        <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <MauiVersion>10.0.90</MauiVersion>
    </PropertyGroup>

    <ItemGroup Condition="$([System.String]::Copy('$(PackageId)').StartsWith('AdamE.AppNav'))">
        <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" PackagePath="/" Visible="false"/>
        <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All"/>
    </ItemGroup>
</Project>
