<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0-android;net10.0-ios;net10.0-maccatalyst</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <UseMaui>true</UseMaui>
    <SingleProject>true</SingleProject>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <ApplicationTitle>AdamE.AppNav.Maui.Tests</ApplicationTitle>
    <ApplicationId>com.adame.appnav.maui.tests</ApplicationId>
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <ApplicationVersion>1</ApplicationVersion>
    <GenerateTestingPlatformEntryPoint>false</GenerateTestingPlatformEntryPoint>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">15.0</SupportedOSPlatformVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">28.0</SupportedOSPlatformVersion>
    <ValidateXcodeVersion>false</ValidateXcodeVersion>
    <SelfContained>true</SelfContained>
  </PropertyGroup>

  <PropertyGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">
    <EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
  </PropertyGroup>

  <PropertyGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios' Or $([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">
    <GenerateProgramFile>false</GenerateProgramFile>
    <EmbedAssembliesIntoAppBundle>true</EmbedAssembliesIntoAppBundle>
  </PropertyGroup>

  <PropertyGroup Condition="'$(RuntimeIdentifier)' == '' And $([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">
    <RuntimeIdentifier>maccatalyst-arm64</RuntimeIdentifier>
  </PropertyGroup>

  <PropertyGroup Condition="'$(RuntimeIdentifier)' == '' And $([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">
    <RuntimeIdentifier>iossimulator-arm64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DeviceRunners.Testing.Targets" Version="0.1.0-preview.12" />
    <PackageReference Include="DeviceRunners.UITesting.Maui" Version="0.1.0-preview.12" />
    <PackageReference Include="DeviceRunners.UITesting.Xunit" Version="0.1.0-preview.12" />
    <PackageReference Include="DeviceRunners.VisualRunners.Maui" Version="0.1.0-preview.12" />
    <PackageReference Include="DeviceRunners.VisualRunners.Xunit" Version="0.1.0-preview.12" />
    <PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.utility" Version="2.9.3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <TrimmerRootAssembly Include="AdamE.AppNav.Maui.Tests" RootMode="all" />
    <TrimmerRootAssembly Include="AdamE.AppNav.Maui" RootMode="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\AdamE.AppNav\AdamE.AppNav.csproj" />
    <ProjectReference Include="..\..\src\AdamE.AppNav.Maui\AdamE.AppNav.Maui.csproj" />
  </ItemGroup>

</Project>
